name: Exercícios 4º bimestre

on:
  push:
  workflow_dispatch:

jobs:
  ex01-loop-while:
    name: ex01-loop-while
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 4-bimestre/ex01-loop-while
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex02-loop-do-while:
    name: ex02-loop-do-while
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 4-bimestre/ex02-loop-do-while
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex03-loop-for:
    name: ex03-loop-for
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 4-bimestre/ex03-loop-for
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test